### PR TITLE
ESDK make install.

### PR DESCRIPTION
**Pull request by nickl-**
Added install target to the esdk makefile which uses the variable DESTDIR for installation prefix and installs the headers to include and the archive to lib.

### CODE REVIEW

**Comment by jamesaross** [comment]
@nickl-,

Thanks for taking the time to include this in the new release.  Some questions...

1. Do you really want `/usr/locals` to be the default installation directory?  I'm not sure that's normally in the users library and include paths.
2. Do you want an `uninstall` or do you expect people to clean up manually?
3. Do you want the option for header-only compilation?  The pull request copies all header files and not all are required for static linking.  The library was designed for a minimal program binary footprint and the header-only compilation actually includes the rest of the C code in addition to the headers (see [./src/shmem_header_only.h](../blob/master/src/shmem_header_only.h)).  The pull request doesn't address this.  There might not be a good way to address this short of using the C Pre-Processor to insert all the code into a single header.

I'm okay with whatever as long as it stays in Makefile.esdk

**Comment by nickl-** [comment]
> 1. Do you really want `/usr/locals` to be the default installation directory?  I'm not sure that's normally in the users library and include paths.

The default is merely a place holder for our purposes we change `DISTDIR` to the build directory.

> 2. Do you want an `uninstall` or do you expect people to clean up manually?

For the purpose of including OpenSHMEM in the ESDK there is no need for an uninstall perse.

> 3. Do you want the option for header-only compilation?  The pull request copies all header files and not all are required for static linking.  The library was designed for a minimal program binary footprint and the header-only compilation actually includes the rest of the C code in addition to the headers (see [./src/shmem_header_only.h](../blob/master/src/shmem_header_only.h)).  The pull request doesn't address this.  There might not be a good way to address this short of using the C Pre-Processor to insert all the code into a single header.

Based on the limited [examples available](https://github.com/USArmyResearchLab/openshmem-epiphany/blob/master/example/e_hello/e_task.c) for the esdk build we can assume only `shmem.h` is required. Would this be sufficient for all use cases though?

**Comment by jamesaross** [comment]
> Based on the limited examples available for the esdk build we can assume only shmem.h is required. Would this be sufficient for all use cases though?

Not _all_ use cases...

If not using the header-only compilation model, which #includes all the code for static compilation, then all that should need to be installed is the shmem.h header and the libshmem_esdk.a library.  This is accomplished with the -DSHMEM_USE_HEADER_ONLY compilation flag or #define SHMEM_USE_HEADER_ONLY before #include "shmem.h".  I found static compilation with the header-only compilation to be superior for Epiphany for both performance and program size (important due to core scratchpad limitations).  But it's not required.

See [./src/shmem_header_only.h](https://github.com/USArmyResearchLab/openshmem-epiphany/blob/master/src/shmem_header_only.h)

**Comment by jamesaross** [comment]
Check out the changes in Makefile.esdk.  They should satisfy your install requirement.  I also use epiphany-elf-cpp to build an installable header so additional code doesn't need to be pulled in (nevermind what I said earlier).

Thanks again.

**Pull request closed without merging**
